id: D1500
type: Detection
summary: Configure monitoring of used artifacts and open-source libraries
description: |
  Implement regular scanning of used artifacts and open-source libraries for known vulnerabilities.
  Set up monitoring of reported issues based on regular scanning results.
  

references:
  - https://owasp.org/www-community/Component_Analysis

metadata:
  - version: 0.1
  - state: draft
